# Generated by Django 2.2.3 on 2020-02-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('studentid', models.IntegerField(blank=True, null=True)),
                ('bookingtime', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
